CREATE OR REPLACE WAREHOUSE TAXIOPS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE TAXIOPS_DB;
CREATE OR REPLACE SCHEMA TAXIOPS_DB.RAW;

CREATE OR REPLACE FILE FORMAT TAXIOPS_DB.RAW.PARQUET_FMT
  TYPE = PARQUET;

CREATE OR REPLACE STAGE TAXIOPS_DB.RAW.TAXI_SILVER_STAGE
  FILE_FORMAT = TAXIOPS_DB.RAW.PARQUET_FMT;

CREATE OR REPLACE TABLE TAXIOPS_DB.RAW.TAXI_TRIPS_SILVER (
  vendor_id STRING,
  pickup_datetime STRING,
  dropoff_datetime STRING,
  pickup_ts TIMESTAMP_NTZ,
  dropoff_ts TIMESTAMP_NTZ,
  pickup_date DATE,
  passenger_count NUMBER,
  trip_distance FLOAT,
  fare_amount FLOAT,
  tip_amount FLOAT,
  total_amount FLOAT,
  payment_type STRING,
  pickup_location_id NUMBER,
  dropoff_location_id NUMBER
);