USE WAREHOUSE TAXIOPS_WH;
USE DATABASE TAXIOPS_DB;
USE SCHEMA RAW;

-- FIX
REMOVE @TAXI_SILVER_STAGE;

PUT 'file:///home/hiron/Tega-Michael-Brian-Project/data/silver/*.parquet'
  @TAXI_SILVER_STAGE
  AUTO_COMPRESS = FALSE
  OVERWRITE = TRUE;

TRUNCATE TABLE TAXI_TRIPS_SILVER;

COPY INTO TAXI_TRIPS_SILVER
FROM @TAXI_SILVER_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;